Skip to content
Search or jump to…

Pull requests
Issues
Marketplace
Explore
 
@jarwow 
WolfgangOfner
/
.NetCoreMicroserviceCiCdAks
1
06
Code
Issues
Pull requests
Actions
Projects
Wiki
Security
Insights
.NetCoreMicroserviceCiCdAks/Docker-CI.yml

Wolfgang added docker CI pipeline
Latest commit c3e5328 on Sep 16, 2020
 History
 0 contributors
39 lines (35 sloc)  1016 Bytes
  
name : Docker-CI
trigger:
  branches:
    include:
      - master

pool:
  vmImage: 'ubuntu-latest'

variables:
  ImageName: 'jarwow/ado-image:$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:  
  - job: Build
    displayName: Build and push Docker image
    steps:
    - task: Docker@1
      displayName: 'Build the Docker image'
      inputs:
        containerregistrytype: 'Container Registry'
        dockerRegistryEndpoint: 'Docker Hub'
        command: 'Build an image'
        dockerFile: '**/Dockerfile'
        imageName: '$(ImageName)'
        includeLatestTag: true
        useDefaultContext: false
        buildContext: '.'
    
    - task: Docker@1
      displayName: 'Push the Docker image to Dockerhub'
      inputs:
        containerregistrytype: 'Container Registry'
        dockerRegistryEndpoint: 'Docker Hub'
        command: 'Push an image'
        imageName: '$(ImageName)'
      condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))

